### ISSUE TITLE
Doesn't work as expected

### ISSUE THREAD

**Issue by mthld** [Write/TangerineUI-Userscript#3]
Hello!

Thanks for your work and sorry for the vague title for this issue.

I just followed the instructions to set it for my instance but it looks like shit haha.

<img width="1360" alt="Screenshot 2024-04-19 at 12 12 09" src="https://github.com/Write/TangerineUI-Userscript/assets/166484083/fe3246e3-afb7-479a-8b30-2d9c10c3571a">

The web browser console doesn't seem to show anything specific:
```
[Info] Injecting TangerineUI 🍊 for Mastodon (js) (content.js, line 281)
[Log] * TangerineUI 🍊 : Mastodon Version Detected is : 4.3.0-alpha.0+glitch * (home, line 90)
[Log] * TangerineUI 🍊 : Version above or equal 4.3.0 found. * (home, line 92)
[Log] * TangerineUI 🍊 : Nounce found (requestAnimationFrame) CwcnbdBzfuMHkd9rOAUJOg== * (home, line 229)
[Log] * TangerineUI 🍊 : Injected theme URI is : //cdn.jsdelivr.net/gh/nileane/TangerineUI-for-Mastodon@v2.0.0-pre4/TangerineUI-purple.min.css * (home, line 67)
[Log] * TangerineUI 🍊 : Nonce found is CwcnbdBzfuMHkd9rOAUJOg== * (home, line 162)
[Log] * TangerineUI 🍊 : (MutationObserver) custom.css or mastodon.*.chunk.css detected, injected TangerineUI's css asap. * (home, line 163)
```

Some information about my instance:
- v4.3.0-alpha.0+glitch
- Default Vanilla flavour selected

Maybe my admin did some manual CSS overwrites, I don't know... :/

Thanks in advance for your help!

**Comment by Write** [comment]
Hello,

Thanks for your issue.

Indeed, your admin seems to have added a custom.css which is loaded after I inject the CSS (`<link rel="stylesheet" href="https://h-i.social/custom.css" media="all">`), hence why it has higher priority over Tangerine. 

Weirdly, even removing this line in my browser doesn't show the theme entirely correctly.

It's supposed to work fine on 4.3-alpha as seen here : https://eldritch.cafe/about

**Comment by mthld** [comment]
Hey,

Thanks for your super quick answer and share your insight regarding this issue!
It's indeed nothing you can do about.

Sad, but OK! I'll see this with my admin.

Thanks a lot!

**Comment by Write** [comment]
FYI, css priority doesn't seem to apply here, as your admin used !important everywhere in his theme, which makes it impossible for me to override it even if I forced it to be loaded injected after custom.css is detected.

Also, I can't manage to understand why all changes are not in custom.css, thus removing custom.css doesn't seem to be enough.
