### ISSUE TITLE
Add option to force light or dark mode instead of relying on prefers-color-scheme

### ISSUE THREAD

**Issue by codenyte** [Write/TangerineUI-Userscript#5]
`prefers-color-scheme` can't be set when using Hardened Firefox/[LibreWolf](https://librewolf.net/) with `privacy.resistFingerprinting` enabled in `about:config`

That's why I would prefer an option to just statically specify the preferred theme in the user script

I tried replacing
```javascript
const theme = window.matchMedia?.("(prefers-color-scheme: dark)").matches ? "dark" : "light";`
```

with a simple 

```javascript
const theme = 'dark';
```

but it had no effect. Do you have an idea why?

**Comment by Write** [comment]
I think that's an issue not related to this user script but related to the resist fingerprinting which stop working once enabled, as to not leak your device color scheme (iirc). 

Try on any website that has support for color scheme and you'll be only able to site it in light mode, even if your system is in dark mode 


But I stumbled upon something that you may try though : https://www.reddit.com/r/LibreWolf/s/tRa71X0v6j

**Comment by Write** [comment]
To add to that : I don't actually do any switching based on color scheme, it was only used to avoid flash while the theme is loading, but all color-scheme behavior are handled by TangerineUI directly, so no, you cannot fix it by just changing this variable. Sorry.
